<?php $this->layout('layouts/main') ?>


<div class="home">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p id="hello">&nbsp;</p>
                <div class="logo">
                    <img src="<?= $assets ?>/images/php-power-micro.png" alt="PHP">
                </div>
                <div class="jumbotron">
                    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                        Bootstrap modal
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
