<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title><?= $appTitle ?></title>
    <meta name="description" content="<?= $appTitle ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="<?= $assets ?>/images/apple-touch-icon.png">
    <link rel="icon" href="<?= $assets ?>/images/favicon.ico" type="image/x-icon">
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
        WebFont.load({
            google: {
                families: ['Open+Sans:400,700:latin']
            }
        });
    </script>
    <link rel="stylesheet" href="<?= $assets ?>/app.css">
</head>
<body>
<?= $this->section('content') ?>


<?php $this->insert('partials/modal'); ?>

<script src="<?= $assets ?>/app.js"></script>
<!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
<script>
    window.ga = function () {
        ga.q.push(arguments)
    };
    ga.q = [];
    ga.l = +new Date;
    ga('create', 'UA-XXXXX-Y', 'auto');
    ga('send', 'pageview')
</script>
<script src="https://www.google-analytics.com/analytics.js" async defer></script>
</body>
</html>
